<?php

/**
 * @file
 * Hook implementations for Social Auth PBS module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_pbs_help($route_name, RouteMatchInterface $route_match): string {
  $output = '';
  if ($route_name == 'help.page.social_auth_pbs') {
    $output = '<h3>' . t('Configuration instructions') . '</h3>';
    $output .= '<p>';
    $output .= t('Configuration instructions and other useful 
        documentation can be found in this module\'s README.md file.');
    $output .= '</p>';
  }
  return $output;
}
